# Generated by Django 4.0.5 on 2022-06-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_userprofile_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.details'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'user')},
        ),
    ]
